import { Atkinson_Hyperlegible } from 'next/font/google';
import '../globals.css';
import '@uploadthing/react/styles.css';
import { ClerkProvider, currentUser, SignOutButton } from '@clerk/nextjs';
import { Popover, PopoverContent, PopoverTrigger } from '~/components/ui/popover';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

const sansFont = Atkinson_Hyperlegible({
	weight: ['400', '700'],
	style: ['italic', 'normal'],
	subsets: ['latin'],
	variable: '--font-sans',
	display: 'auto'
});

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const user = await currentUser();
	return (
		<ClerkProvider>
			<html lang="en" className={sansFont.variable}>
				<body className={sansFont.className}>
					<nav className="px-4 py-2 flex border-b-2 border-b-slate-100">
						{!user ? (
							<a href="/sign-in">Sign in</a>
						) : (
							<Popover>
								<PopoverTrigger className="ml-auto">
									{typeof user.publicMetadata.profilePicSrc === 'string' ? (
										<img
											className="w-[3rem] rounded-full"
											src={user.publicMetadata.profilePicSrc}
											alt={user.firstName ?? ''}
										/>
									) : (
										user.firstName
									)}
								</PopoverTrigger>
								<PopoverContent className="bg-white rounded-md">
									<SignOutButton />
								</PopoverContent>
							</Popover>
						)}
					</nav>
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
