import { Atkinson_Hyperlegible } from 'next/font/google';
import './globals.css';
import '@uploadthing/react/styles.css';
import { ClerkProvider, currentUser } from '@clerk/nextjs/app-beta';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

const sansFont = Atkinson_Hyperlegible({
	weight: ['400', '700'],
	style: ['italic', 'normal'],
	subsets: ['latin'],
	variable: '--font-sans',
	display: 'auto'
});

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const user = await currentUser();
	return (
		<ClerkProvider>
			<html lang="en" className={sansFont.variable}>
				<body className={sansFont.className}>
					<nav>
						{user ? (
							<a href="/profile">
								{typeof user.publicMetadata.profilePicSrc === 'string' ? (
									<img src={user.publicMetadata.profilePicSrc} alt={user.firstName} />
								) : (
									user?.firstName
								)}
							</a>
						) : null}
					</nav>
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
