import { Atkinson_Hyperlegible } from 'next/font/google';
import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

const bodyFont = Atkinson_Hyperlegible({
	weight: ['400', '700'],
	style: ['italic', 'normal'],
	subsets: ['latin'],
	variable: '--font-sans',
	display: 'auto'
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className={bodyFont.variable}>
			<body className={bodyFont.className}>{children}</body>
		</html>
	);
}
